config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "chatrooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :chatrooms, only: [:show, :index, :new, :create] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  before_create do
    opentok = OpenTok::OpenTok.new '47557071', '5d3a8f493e5219176682adf8f82d924be6afe32b'
    session = opentok.create_session
    self.vonage_session_id = session.session_id
  end
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!


  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    opentok = OpenTok::OpenTok.new '47557071', '5d3a8f493e5219176682adf8f82d924be6afe32b'
    @token = opentok.generate_token @chatroom.vonage_session_id, { name: current_user.nickname }
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to chatroom_url(@chatroom), notice: "chatRoom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name, :vonage_session_id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      # ActionCable.server.broadcast("chatroom-#{@chatroom.id}",
      #                              render_to_string(partial: 'messages/message', locals: { message: @message }))
      ChatroomChannel.broadcast_to(@chatroom,
                                render_to_string(partial: 'messages/message', locals: { message: @message }))
      redirect_to chatroom_path(@chatroom)
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/_chatroom.html.erb
<div id="<%= dom_id chatroom %>">
  <h5>
    <strong>Sala:</strong>
    <%= chatroom.name %>
  </h5>


</div>

app/views/chatrooms/_form.html.erb
<%= simple_form_for(@chatroom) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name,
                label: 'Nome' %>

  </div>

  <div class="form-actions">
    <%= f.button :submit,
                  'Criar sala', class: 'btn btn-outline-dark btn-new-room' %>
  </div>
<% end %>

app/views/chatrooms/index.html.erb
<div class="container mt-5">
  <div id="Chatrooms">
    <div class="row">
      <% @chatrooms.each do |chatroom| %>
        <div class="card card-room">
          <%= link_to(chatroom) do %>
            <div class="card-body">
              <%= render chatroom %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <%= link_to "Nova sala", new_chatroom_path, class: 'btn btn-outline-dark btn-new-room' %>
    </div>
  </div>
</div>

app/views/chatrooms/new.html.erb
<div class="container mt-5">
  <div class="card card-login">
    <div class="card-body">
      <h1>Nova Sala</h1>
      <%= render "form", chatroom: @chatroom %>
      <br>
      <div>
        <%= link_to "Voltar", chatrooms_path, class: 'btn btn-outline-secondary btn-new-room' %>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="container chatroom">
  <h1>#<%= @chatroom.name %></h1>
  <div id="videos"
     data-controller="vonage"
     data-vonage-api-key="47557071"
     data-vonage-session-id="<%= @chatroom.vonage_session_id %>"
     data-vonage-token="<%= @token %>"
     data-vonage-name="<%= current_user.nickname %>"
  >
  </div>

  <div class="messages"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  >
    <% @chatroom.messages.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
  </div>
  <%= simple_form_for [@chatroom, @message], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: "Say something in ##{@chatroom.name}"%>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>RailsActionCableChat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.nickname %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to chatrooms_path, class: 'btn btn-outline-dark btn-new-room' do %>
      Todas as salas
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item dropdown">
            <%= image_tag "usuario.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>